version: '3.1'

services:
  
  dbadmin:
    image: crunchydata/crunchy-pgadmin4:centos7-10.5-2.1.0
    container_name: pgadmin4
    hostname: pgadmin4
    volumes:
      - pga4volume:/var/lib/pgadmin
    ports:
      - "5050:5050"
    env_file:
      - pgadmin-env.list


volumes:
  pga4volume:
    external: true

